groups:
  - name: application
    rules:
      # Application Health
      - alert: ApplicationDown
        expr: up{job="heypeter-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "HeyPeter Academy application is down"
          description: "Application {{ $labels.instance }} has been down for more than 1 minute."

      # High Response Time
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}."

      # Database Connection Issues
      - alert: DatabaseConnectionFailure
        expr: db_connections_failed_total > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failures"
          description: "{{ $value }} database connection failures in the last minute."

      # Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% on {{ $labels.instance }}."

      # CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 10 minutes on {{ $labels.instance }}."

      # Disk Space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }}."

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiringSoon
        expr: ssl_certificate_expiry_days < 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days."

  - name: business_metrics
    rules:
      # User Registration Rate
      - alert: LowUserRegistrationRate
        expr: rate(user_registrations_total[1h]) < 0.01
        for: 2h
        labels:
          severity: warning
        annotations:
          summary: "Low user registration rate"
          description: "User registration rate is {{ $value | humanize }} per second."

      # Class Booking Rate
      - alert: LowClassBookingRate
        expr: rate(class_bookings_total[1h]) < 0.005
        for: 4h
        labels:
          severity: info
        annotations:
          summary: "Low class booking rate"
          description: "Class booking rate is {{ $value | humanize }} per second."

      # Payment Failures
      - alert: HighPaymentFailureRate
        expr: rate(payment_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is {{ $value | humanizePercentage }}."

  - name: infrastructure
    rules:
      # Redis Down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} has been down for more than 1 minute."

      # High Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 90% on {{ $labels.instance }}."

      # Nginx Down
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx is down"
          description: "Nginx instance {{ $labels.instance }} has been down for more than 1 minute."