version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: heypeter-academy-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./public:/app/public:ro
    networks:
      - heypeter-network
    restart: unless-stopped

  # Development configuration (use with docker-compose -f docker-compose.yml -f docker-compose.dev.yml up)
  # This overrides the production settings for development