# Prometheus Configuration for HeyPeter Academy LMS
# This configuration defines monitoring targets and scraping rules

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'heypeter-academy'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Application instances
  - job_name: 'heypeter-app'
    static_configs:
      - targets:
        - 'app1:3000'
        - 'app2:3000'
        - 'app3:3000'
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets:
        - 'nginx-exporter:9113'
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets:
        - 'postgres-exporter:9187'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets:
        - 'redis-exporter:9121'
    scrape_interval: 30s

  # HAProxy metrics (if using HAProxy)
  - job_name: 'haproxy'
    static_configs:
      - targets:
        - 'haproxy:8404'
    metrics_path: '/stats/prometheus'
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'
    scrape_interval: 30s

  # Blackbox exporter for external monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://heypeter-academy.com
        - https://heypeter-academy.com/health
        - https://heypeter-academy.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'ssl-exporter'
    static_configs:
      - targets:
        - 'ssl-exporter:9219'
    params:
      target: ['heypeter-academy.com:443']

  # Custom application metrics
  - job_name: 'heypeter-custom-metrics'
    static_configs:
      - targets:
        - 'app1:3000'
        - 'app2:3000'
        - 'app3:3000'
    metrics_path: '/api/metrics/custom'
    scrape_interval: 60s
    honor_labels: true

  # Supabase metrics (if available)
  - job_name: 'supabase'
    static_configs:
      - targets:
        - 'supabase-metrics:9090'
    scrape_interval: 30s
    honor_labels: true
    # This might need authentication
    basic_auth:
      username: 'monitoring'
      password: 'monitoring-password'

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    # Authentication if needed
    # basic_auth:
    #   username: 'user'
    #   password: 'password'

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 50GB
    wal-compression: true