# Backup Configuration for HeyPeter Academy LMS
# This file defines backup strategies, schedules, and retention policies

backup_config:
  # General Settings
  environment: production
  backup_root: /backup/heypeter-academy
  encryption_enabled: true
  compression_enabled: true
  notification_enabled: true
  
  # Database Backup Configuration
  database:
    # Supabase PostgreSQL backup
    enabled: true
    type: postgresql
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention:
      daily: 7    # Keep 7 daily backups
      weekly: 4   # Keep 4 weekly backups
      monthly: 12 # Keep 12 monthly backups
      yearly: 3   # Keep 3 yearly backups
    
    # Connection settings
    connection:
      host: "${SUPABASE_DB_HOST}"
      port: 5432
      database: postgres
      username: postgres
      password: "${SUPABASE_DB_PASSWORD}"
      ssl_mode: require
    
    # Backup options
    options:
      format: custom  # PostgreSQL custom format
      compression: 9  # Maximum compression
      verbose: true
      no_owner: true
      no_privileges: true
      exclude_tables:
        - audit_logs_old
        - temp_*
        - cache_*
    
    # Storage locations
    destinations:
      - type: local
        path: "${BACKUP_ROOT}/database"
        enabled: true
      - type: s3
        bucket: "heypeter-backups"
        prefix: "database/"
        region: "us-east-1"
        enabled: true
      - type: gcs
        bucket: "heypeter-backups-gcs"
        prefix: "database/"
        enabled: false

  # Application Files Backup
  application:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM
    retention:
      daily: 3
      weekly: 2
      monthly: 6
    
    # Paths to backup
    include_paths:
      - "/app/uploads"
      - "/app/logs"
      - "/app/config"
      - "/etc/nginx"
      - "/etc/ssl"
    
    # Paths to exclude
    exclude_patterns:
      - "*.tmp"
      - "*.log"
      - "node_modules/"
      - ".git/"
      - "*.cache"
    
    # Storage destinations
    destinations:
      - type: local
        path: "${BACKUP_ROOT}/application"
        enabled: true
      - type: s3
        bucket: "heypeter-backups"
        prefix: "application/"
        region: "us-east-1"
        enabled: true

  # User Data Backup (Additional protection for critical data)
  user_data:
    enabled: true
    schedule: "0 1 * * *"  # Daily at 1 AM
    retention:
      daily: 14   # Keep 14 daily backups
      weekly: 8   # Keep 8 weekly backups
      monthly: 24 # Keep 24 monthly backups
    
    # Tables to backup separately
    tables:
      - profiles
      - students
      - teachers
      - courses
      - classes
      - enrollments
      - student_hours
      - leave_requests
    
    destinations:
      - type: local
        path: "${BACKUP_ROOT}/user_data"
        enabled: true
      - type: s3
        bucket: "heypeter-backups"
        prefix: "user_data/"
        region: "us-east-1"
        enabled: true

  # Configuration Backup
  configuration:
    enabled: true
    schedule: "0 4 * * 0"  # Weekly on Sunday at 4 AM
    retention:
      weekly: 12
      monthly: 12
    
    # Configuration files and directories
    include_paths:
      - "/deployment"
      - "/docker-compose*.yml"
      - "/nginx.conf"
      - "/haproxy.cfg"
      - "/.env.production"
      - "/scripts"
    
    destinations:
      - type: local
        path: "${BACKUP_ROOT}/configuration"
        enabled: true
      - type: s3
        bucket: "heypeter-backups"
        prefix: "configuration/"
        region: "us-east-1"
        enabled: true

  # Log Backup
  logs:
    enabled: true
    schedule: "0 23 * * *"  # Daily at 11 PM
    retention:
      daily: 30
      monthly: 6
    
    # Log directories
    include_paths:
      - "/var/log/nginx"
      - "/var/log/haproxy"
      - "/app/logs"
      - "/deployment/logs"
    
    # Compress logs before backup
    compression: gzip
    
    destinations:
      - type: local
        path: "${BACKUP_ROOT}/logs"
        enabled: true
      - type: s3
        bucket: "heypeter-backups"
        prefix: "logs/"
        region: "us-east-1"
        enabled: false  # Logs can be large, local only by default

# Storage Configuration
storage:
  local:
    base_path: /backup/heypeter-academy
    permissions: "0750"
    owner: backup
    group: backup
  
  s3:
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    region: "us-east-1"
    storage_class: STANDARD_IA
    server_side_encryption: AES256
  
  gcs:
    service_account_key: "${GCS_SERVICE_ACCOUNT_KEY}"
    project_id: "${GCP_PROJECT_ID}"
    storage_class: NEARLINE

# Encryption Settings
encryption:
  enabled: true
  algorithm: AES256
  key_file: /etc/backup/encryption.key
  
  # GPG encryption (alternative)
  gpg:
    enabled: false
    recipient: backup@heypeter-academy.com
    key_id: "0x1234567890ABCDEF"

# Notification Settings
notifications:
  email:
    enabled: true
    smtp_host: "${EMAIL_SERVER_HOST}"
    smtp_port: 587
    smtp_username: "${EMAIL_SERVER_USER}"
    smtp_password: "${EMAIL_SERVER_PASSWORD}"
    from_address: "backup@heypeter-academy.com"
    to_addresses:
      - "admin@heypeter-academy.com"
      - "devops@heypeter-academy.com"
    
    # Notification triggers
    on_success: false  # Only notify on failure by default
    on_failure: true
    on_warning: true
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#alerts"
    username: "Backup Bot"
  
  webhook:
    enabled: false
    url: "${WEBHOOK_URL}"
    method: POST
    headers:
      Authorization: "Bearer ${WEBHOOK_TOKEN}"

# Monitoring and Health Checks
monitoring:
  enabled: true
  
  # Health check intervals
  database_check: "*/30 * * * *"  # Every 30 minutes
  storage_check: "0 */6 * * *"    # Every 6 hours
  
  # Alert thresholds
  thresholds:
    backup_age_hours: 26          # Alert if latest backup is older than 26 hours
    storage_usage_percent: 85     # Alert if storage is 85% full
    backup_duration_hours: 4      # Alert if backup takes longer than 4 hours
    failed_backups_count: 2       # Alert after 2 consecutive failures

# Recovery Settings
recovery:
  # Point-in-time recovery settings
  point_in_time:
    enabled: true
    wal_retention_hours: 168  # 7 days
  
  # Staging environment for testing recovery
  staging:
    enabled: true
    database_name: "heypeter_staging_restore"
    test_schedule: "0 6 * * 0"  # Weekly on Sunday at 6 AM
  
  # Recovery verification
  verification:
    enabled: true
    test_queries:
      - "SELECT COUNT(*) FROM profiles;"
      - "SELECT COUNT(*) FROM students;"
      - "SELECT COUNT(*) FROM teachers;"
      - "SELECT MAX(created_at) FROM audit_logs;"

# Disaster Recovery
disaster_recovery:
  # RTO (Recovery Time Objective)
  rto_hours: 4
  
  # RPO (Recovery Point Objective)
  rpo_hours: 1
  
  # Secondary site configuration
  secondary_site:
    enabled: false
    region: "us-west-2"
    database_replica: true
    application_standby: true
  
  # Failover procedures
  failover:
    automated: false
    procedures_url: "https://docs.heypeter-academy.com/disaster-recovery"