apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Prometheus Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    
  - name: PostgreSQL
    type: postgres
    url: ${DATABASE_URL}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: require
      database: postgres
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400